version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: pactoteste
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dv0000
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pactoteste
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: dv0000
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres-data:
